### ISSUE TITLE
Custom functions should not be defined in template files

### ISSUE THREAD

**Issue by pnikolov** [AleksandarDzh/CarBlogTheme#1]
https://github.com/AleksandarDzh/CarBlogTheme/blob/29593b1a3342056edc602888e268e90df41c3e98/archive.php#L67-L97

The `compose_url()` function should not be defined in the `archive.php` file - all the template files defined in the WordPress [Template Hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/) should be used only for templating purposes.

Also, can you clarify the double filtering of the `$args` for `$slug` and the actual conditions, they seem reversed.

**Comment by AleksandarDzh** [comment]
The double filtering was pointless because it was basically the same. It's most likely something I forgot to remove. Thank you
